version: '2'
services:
  zabbix-db:
    image: mariadb
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
    restart: unless-stopped
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=zabbix
      - DB_SERVER_HOST=zabbix-db
    restart: unless-stopped
    links:
      - zabbix-db:zabbix-db
      - zabbix-agent:zabbix-agent
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=zabbix
      - DB_SERVER_HOST=zabbix-db
      - ZBX_SERVER_HOST=zabbix-server
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    links:
      - zabbix-db:zabbix-db
      - zabbix-server:zabbix-server
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
    restart: unless-stopped
    privileged: true
    links:
      - zabbix-server:zabbix-server

volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
