version: '2'
services:
  zabbix-db:
    image: mariadb
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD="123456"
      - MYSQL_USER="root"
      - DB_SERVER_HOST="zabbix-db"
    links:
      - zabbix-db:zabbix-db
volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
